# development environment

server:
  port: 8080

# MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingapp
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #Eureka Client Configuration
  application:
    name: CUSTOMER-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
